#pragma once

#define DGNSRSINKFLAG_SENDBEGINUTT     0x01
#define DGNSRSINKFLAG_SENDENDUTT       0x02
#define DGNSRSINKFLAG_SENDATTRIB       0x08
#define DGNSRSINKFLAG_SENDINTERFERENCE 0x10
#define DGNSRSINKFLAG_SENDSOUND        0x20
#define DGNSRSINKFLAG_SENDJITPAUSED    0x40
#define DGNSRSINKFLAG_SENDERROR        0x80
#define DGNSRSINKFLAG_SENDPROGRESS     0x100
#define DGNSRSINKFLAG_SENDMIMICDONE    0x200
#define DGNSRSINKFLAG_SENDALL          0x3FF

#define DGNDICTSINKFLAG_SENDTEXTCHANGED    0x00010000
#define DGNDICTSINKFLAG_SENDTEXTSELCHANGED 0x00020000
#define DGNDICTSINKFLAG_SENDJITPAUSE       0x00100000

#define DGNSRGRAMSINKFLAG_SENDPHRASEHYPO 	  0x2000
#define DGNSRGRAMSINKFLAG_SENDPHRASEFINISH  0x4000
#define DGNSRGRAMSINKFLAG_SENDFOREIGNFINISH 0x8000
